### ISSUE TITLE
Article embed options

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/tiny-news-demo#14]
Use each service's various options for embedding (aka copy & paste html)? 

Use our own or quasi-standard short codes (ex `[tweet id=1234568901]`)? 

Transform urls to embeds (`https://twitter.com/BBCWorld/status/1262182320209092609` -> tweet)?

* twitter
* youtube
* instagram
* facebook

**Comment by jacqui** [comment]
So far I've tried embedding a tweet and a youtube video. I did this via both services' embed codes. The experience isn't so great-looking on the Google Docs editing side, but both pieces of content at least do come through in the published HTML. Both require some design and usability love + style.

<img width="727" alt="google docs embed codes" src="https://user-images.githubusercontent.com/3397/82005482-d9bdfb00-96a8-11ea-8cd4-b167e84de9fb.png">

<img width="1427" alt="gatsby published article embeds" src="https://user-images.githubusercontent.com/3397/82005488-ddea1880-96a8-11ea-8558-fe46d0619600.png">

**Comment by TylerFisher** [comment]
Weird that the Twitter script doesn't seem to work. It's not getting stripped out -- I can see it in the DOM.

**Comment by jacqui** [comment]
**try:** Google app script with document template to generate a short code that the gatsby app could parse?

**Comment by jacqui** [comment]
So... I spent some time with the google app scripts editor today. We can do a fair amount of things, fairly easily... with some issues.

It really depends on what we want the user experience to be like. I'm admittedly very technical/tech-savvy, so what I would expect in this is probably not the norm. I prefer a more streamlined approach: my fave is to include a mere url and have it expanded into an embed.

However, I realize that can be limiting: how do you specify a width, for instance, with just a URL?

I guess I'm not sure of the best way to accomplish this.

Anyway, some possibilities:

* new menu item that opens a window with some choices, including a text field for a URL of the content to embed, plus perhaps an optional width & height text field, and inserts a short code
* new menu item that grabs the currently selected text (in theory, a URL to content) and replaces it with a short code

Some issues:

* it's actually hard to insert text at the current cursor position; there are methods to `getCursor` for instance but I found it fails to do so at least 50% of the time
* replacing selections is also a bit unreliable; what if the selection is within a bigger block of text? 
* any short code we replace the text with will then have to be parsed at publishing time
* also, any short code we insert in the document can be edited, accidentally for instance, and cause an error

I am trying not to overthink this, really :) Can we discuss a good way forward, with the understanding that we may need to alter it even after playing around some more?

I'm pasting the script below to keep all of this together with our notes.

```
function insertShortcode(url) {
  var shortCode = `[embed src=${url}]`;

  // I couldn't get this to find the cursor reliably :(
  //var cursor = DocumentApp.getActiveDocument().getCursor();
  //if (cursor) {
    // Attempt to insert text at the cursor position. If the insertion returns null, the cursor's
    // containing element doesn't allow insertions, so show the user an error message.
    //var element = cursor.insertText(shortCode);
    //if (!element) {
    //  DocumentApp.getUi().alert('Cannot insert text here.');
    //}
  //} else {
    //DocumentApp.getUi().alert('Cannot find a cursor.');
  //}


  var body = DocumentApp.getActiveDocument().getBody();
  body.appendParagraph(shortCode); // this appends the shortcode to the end of the document, not really ideal
}

function onOpen() {
  DocumentApp.getUi() // Or SpreadsheetApp or SlidesApp or FormApp.
      .createMenu('Embed from Social')
      .addItem('Selected URL', 'replaceSelectedText')
      .addItem('Enter URL', 'showPrompt')
      .addToUi();
}

function replaceSelectedText() {
      var selection = DocumentApp.getActiveDocument().getSelection()
      
      if (selection) {
        var elements = selection.getRangeElements();

        for (var i = 0; i < elements.length; i++) {
          var element = elements[i];

          // Only modify elements that can be edited as text; skip images and other non-text elements.
          if (element.getElement().editAsText) {
            var text = element.getElement().editAsText();
            var url = text.getText();
            var shortCode = `[embed src=${url}]`;

            // Bold the selected part of the element, or the full element if it's completely selected.
            // does it being partial matter?
            if (element.isPartial()) {
              DocumentApp.getUi().alert(`selection is partial, not entire element ${element.getStartOffset()} ${element.getEndOffsetInclusive()}`);
            }
            
            text.setText(shortCode);
          }
        }
      }
}

function showPrompt() {
  
  var ui = DocumentApp.getUi(); // Same variations.

  var result = ui.prompt(
    'Embed from social',
    'Enter the URL of the content you\'d like to embed below:',
      ui.ButtonSet.OK_CANCEL);

  // Process the user's response.
  var button = result.getSelectedButton();
  var url = result.getResponseText();
  if (button == ui.Button.OK) {
    insertShortcode(url);
    ui.alert('Inserted a shortcode to embed the content at ' + url + '.');
  } else if (button == ui.Button.CANCEL) {
    ui.alert('I didn\'t get a URL.');
  } else if (button == ui.Button.CLOSE) {
    ui.alert('You closed the dialog.');
  }
}
```
