### ISSUE TITLE
Integrate Pico

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/tiny-news-demo#16]
I'm not sure what needs to happen here yet, but Pico handles customer and payment management (https://trypico.com/).

**Comment by TylerFisher** [comment]
Blocked until we talk to Pico about this.

**Comment by jacqui** [comment]
Heather and I have a meeting with Pico tomorrow.

**Comment by jacqui** [comment]
Quick status update: this integration work is underway, but currently stalled because of an issue with the pico widget. I have a conversation open with Pico support.

**Comment by jacqui** [comment]
Progress! While waiting for Pico to get back to me, I figured out how to properly load it at least. Now I'm getting an error on "Invalid token" so I'm onto that...

**Comment by jacqui** [comment]
"Invalid token" was due to a URL mismatch - the url the page is on needs to match whatever you specify in the pico settings. I'll update the PR now.

**Comment by jacqui** [comment]
PR open - this will need some work going forward, but the initial integration is done ✌️
