### ISSUE TITLE
Setup for amp

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/tiny-news-demo#3]
Setup AMP versions of the templates. A good start might be https://www.gatsbyjs.org/packages/gatsby-plugin-amp/

**Comment by TylerFisher** [comment]
Merged, looks great. A question I have: if our standard article pages conform to amp, do we need to build separate versions?

**Comment by jacqui** [comment]
Good question. I'll look into it today.

**Comment by jacqui** [comment]
I've switched the default to AMP - our article pages shouldn't have incompatibilities with AMP afaik.
