### ISSUE TITLE
Build "kitchen sink" demo story

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/tiny-news-demo#32]
A demo story should:

- Be a complete news article (doesn't matter what the source is, or if it's cobbled together from a few things)
- Include photos, embeds, tables, and other style possibilities from Google Docs
- Have complete social/SEO metadata

**Comment by jacqui** [comment]
... this is in progress...

**Comment by jacqui** [comment]
Google Doc: https://docs.google.com/document/d/1rDYGpP5733-aKS662DeSEpouepo3XWknlBKYfNBfV2E/edit

Headline: US death toll passes 100,000

Includes: embedded Youtube video, table (lifted from the NYT), is tagged and has full metadata.
