### ISSUE TITLE
Still getting blank pages after navigating around the site a few times

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/tiny-news-demo#40]
Completely mystifying, no idea why

**Comment by TylerFisher** [comment]
I can pretty predictably make this happen if I do the following:

1. Load localhost:8000
2. Navigate to an article page
3. Click the title in the navbar to go back to the home page (or just go back in the browser)
4. Navigate to an article page. It can even be the same one.

Then I have blank pages.

**Comment by TylerFisher** [comment]
Only happens in Firefox.

**Comment by jacqui** [comment]
I'm investigating this. I'm wondering if this has anything to do with the problem:

https://github.com/gatsbyjs/gatsby/issues/23647

I see this error in Firefox only:

```
The connection to http://localhost:8000/__webpack_hmr was interrupted while the page was loading.
```

Anyway though I'm still trying to fix the problem. I'll post here with any updates.

**Comment by jacqui** [comment]
After my last comment, I had pretty much resigned myself to starting a new gatsby site from scratch and then working in each customisation, one at a time. 

Then, after doing some digging and finding others (using gatsby or not) reporting blank pages in FF and a webpack_hmr error, it kinda seemed like this was a problem in one or more of the gatsby dependencies. So I decided to `npm outdated` and `npm update --save` on each reported outdated dep, and then republish the site using `gatsby clean && gatsby develop` locally. 

Prior to updating deps, I was consistently getting blank pages in FF - in fact, I would even get a blank by simply reloading an article page after it had properly rendered. 

After updating the deps, I have not seen a blank page in FF. I'm going to run `gatsby build && gatsby serve` and test in FF (and Chrome) to ensure the published version also works now.
