### ISSUE TITLE
Are there other ways to support embeds without the Google Apps Script?

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/tiny-news-demo#58]
Let's assume we can't get the script to travel with new stories. What else can we do?

**Comment by jacqui** [comment]
Perhaps we could supply straightforward instructions on how to embed, like:

* to embed content, for instance, a YouTube video, use a shortcode: `[embed src=https://youtu.be/xwRrUviPD_A]`
* to embed content, paste the link on its own line:

```
Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

https://youtu.be/xwRrUviPD_A

Lorem ipsem doler. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
```

If we're not offering additional options on the embedded content, it seems to me that a URL on its own is the simplest solution. Is that problematic or too unclear in intention? 

What do you think?

**Comment by TylerFisher** [comment]
Yeah, I think the latter makes sense as a backup. Let's see where Google gets us.
