### ISSUE TITLE
Integrate Coral Project comments

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/tiny-news-demo#64]
Much like other services, my main question about Coral is if we can run one instance of the server-side component for all of TNC so that we can share costs among the many organizations.

**Comment by jacqui** [comment]
I'm now working on deploying Coral to Heroku (https://docs.coralproject.net/talk/)

**Comment by jacqui** [comment]
Cool, I've made a bit of progress on Coral: it's setup on Heroku at https://coral-talk-news-catalyst.herokuapp.com/admin/dashboard and I've updated PR #94 to use this installation. I'm having some trouble getting story metadata - like the story title - to show up in Coral, but I'm working on it.
