### ISSUE TITLE
Fix deploy check on mixed/insecure content

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/tiny-news-demo#72]
One of Netlify's deploy checks is consistently failing, causing any PR to show a check failure in exactly the same way. I'd like to both fix the actual issue and ensure that PRs are reliably passing before merging in. I worry this could mask another issue if the checks are failing all the time.

Insecure mixed content detected in
affectionate-boyd-223008
Although you have enabled HTTPS on your site, we’ve detected some content that’s still being served over an HTTP connection. This phenomenon, called mixed content, happens when both HTTP and HTTPS are being used to load the same page.

Mixed content impacts the security and user experience of your site, and prevents browsers from protecting your users from malicious attacks.

We’ve added some information to your deploy log to help you find the problem. Most major browsers also provide tools to help you find and fix mixed content. They alert you about mixed content in the JavaScript console. To find this console, you can right-click in any page of your site, select “Inspect Element”, and then select “Console”.

Google’s Developer Guides provide a more extensive description about this problem and its solution.

**Comment by TylerFisher** [comment]
It's weird, I don't actually see any mixed content warnings in the console.

**Comment by jacqui** [comment]
Me either, I just see it in the logs. I noticed that I had accidentally set the canonical url for AMP to "http" instead of "https" - changing that now in a branch to see if the deploy still complains.

**Comment by jacqui** [comment]
That was it! (and that was _quick_)

```
All linked resources are secure

Congratulations! No insecure mixed content found in your files.
```
