### ISSUE TITLE
Fix build error in search branch on `window` def

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/tiny-news-demo#74]
From [the build logs on feature/search](https://app.netlify.com/sites/affectionate-boyd-223008/deploys/5ed98dec01b0cd0007fe19b2):

10:14:06 AM: failed Building static HTML for pages - 4.108s
10:14:06 AM: 
10:14:06 AM: 
10:14:06 AM: error "window" is not available during server side rendering.
10:14:06 AM: 
10:14:06 AM: 
10:14:06 AM: 
10:14:06 AM:   WebpackError: ReferenceError: window is not defined
10:14:06 AM:   
10:14:06 AM:   - build-html.js:110 doBuildPages
10:14:06 AM:     [repo]/[gatsby]/dist/commands/build-html.js:110:24

This happens during `gatsby build` when you reference `window.anything` outside of a `componentDidMount` or an appropriate hook. When will I learn...

**Comment by jacqui** [comment]
Fixed and pushed to open PR for feature/search.

**Comment by maduby** [comment]
Hey, I've got this issue here now, too, although I haven't changed the code and it ran just fine before –– and I'm quite sure I am not using window. anywhere in my code on the server side... Did you find any other related issues to this?

**Comment by trevorpfiz** [comment]
I seem to have had this come up as well, but with document instead of window.  Maybe it is unrelated, but I am unable to find what is wrong.
