### ISSUE TITLE
Make images larger on standard ArticleLink component

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/tiny-news-demo#79]
A few examples to take a look at:

Politico:
<img width="845" alt="Screen Shot 2020-06-08 at 12 00 13 PM" src="https://user-images.githubusercontent.com/1077075/84053277-aefd5480-a97f-11ea-8eba-2b070def4d4d.png">

NPR:
<img width="937" alt="Screen Shot 2020-06-08 at 12 01 02 PM" src="https://user-images.githubusercontent.com/1077075/84053328-bf153400-a97f-11ea-903f-0f86a06105ed.png">

The Atlantic:
<img width="614" alt="Screen Shot 2020-06-08 at 12 01 41 PM" src="https://user-images.githubusercontent.com/1077075/84053397-d6542180-a97f-11ea-96fc-c7bb675beb62.png">

**Comment by jacqui** [comment]
@ian-walker I think this might have been done already, but I'm not sure. Could you confirm & close this issue if it's already taken care of?

<img width="1157" alt="Screen Shot 2020-06-17 at 1 06 54 pm" src="https://user-images.githubusercontent.com/3397/84850627-8706a300-b09b-11ea-8125-605ba1c4933e.png">

`</cleaning-up-issues>` 😄
