### ISSUE TITLE
Default ad components

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/tiny-news-demo#82]
We don't have access to the API yet, but the ad platform we're considering using has some [default ad types](https://docs.whereby.us/Creators/DefaultAdTypes.html). We should build some display components that match these default ad types. There is markup in those docs to emulate. 

The five types are:

- Text ad
- Image with text ad
- Banner ad
- Expanded text ad
- Expanded text with image ad

We'll want a component for each of those types. Each component should:

- Take the text and/or image of the ad as props to the component (eventually, we'll supply the props via an API request to the platform, but we're not there yet).
- Be reusable across homepage, story pages and tag pages

**Comment by jacqui** [comment]
PR for this work done and merged
